# ANSWER 1:

In [3]:
import numpy as np

In [6]:
arr=np.array(range(2,51,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# ANSWER 2:

In [15]:
l1 = [int(l1) for l1 in input("Enter 5 elements in list 1: ").split()]
#print("Number of list is: ", l1) 

l2 = [int(l2) for l2 in input("Enter 5 elements in list 2: ").split()]
#print("Number of list is: ", l2) 
arr1=np.array(l1)
arr2=np.array(l2)

print("List1 converted into array1: ", arr1) 
print("List2 converted into array2: ", arr2) 

arr3=np.concatenate((arr1,arr2))
print("Concatenation : ", arr3)
print("Sorted array :",np.sort(arr3))

Enter 5 elements in list 1:  1 3 5 7 9
Enter 5 elements in list 2:  2 4 6 8 10


List1 converted into array1:  [1 3 5 7 9]
List2 converted into array2:  [ 2  4  6  8 10]
Concatenation :  [ 1  3  5  7  9  2  4  6  8 10]
Sorted array : [ 1  2  3  4  5  6  7  8  9 10]


# ANSWER 3:

In [18]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
print("Number of dimensions: ", arr.ndim)
 
print("Shape of the array: ", arr.shape)
 
# Printing size of array
print("Size of the array: ", arr.size)
 

Number of dimensions:  2
Shape of the array:  (2, 3)
Size of the array:  6


# ANSWER 4:

In [30]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])
x1_new = x1[:, np.newaxis]
x3= x1_new+x2
print(x1_new)    

[[1]
 [2]
 [3]
 [4]
 [5]]


In [33]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
x= a[:, np.newaxis] + b
x

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

# ANSWER 5:

In [37]:
in_arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3],[ 4, 5, 6]] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6],[ 7, 8, 9]] ) 
print ("2nd Input array : \n", in_arr2)  
  
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output Horizontal stacked array :\n", out_arr)

out_arr = np.vstack((in_arr1, in_arr2)) 
print ("Output Vertical stacked array :\n", out_arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]
 [ 7  8  9]]
Output Horizontal stacked array :
 [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]
 [ 4  5  6  7  8  9]]
Output Vertical stacked array :
 [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [ 4  5  6]
 [-4 -5 -6]
 [ 7  8  9]]


# ANSWER 6:

In [38]:
a_list = [1, 1, 2, 2, 3]
a_set = set(a_list)
number_of_unique_values = len(a_set)
print("Uique elements: \n", a_set)
print("No. of Unique elements",number_of_unique_values)

Uique elements: 
 {1, 2, 3}
No. of Unique elements 3
